version: '3'
services:
  mongo:
    image: mongo:4.2.22
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    restart: always
    image: node-ts-clean-api
    command: npm start
    volumes:
      - ./dist:/usr/src/node-ts-clean-api/dist
    ports:
      - "5050:5050"
    links:
      - mongo
